import { StudioClientCore } from "../platform/core.ts";

export namespace StudioClientElements {
  export type StudioElement = HTMLElement & {
    checked: boolean;
    disabled: boolean;
    files: FileList | null;
    open: boolean;
    options: HTMLOptionsCollection;
    placeholder: string;
    selectedOptions: HTMLCollectionOf<HTMLOptionElement>;
    size: number;
    value: string;
  };

  type ElementCore = {
    optionalElement: (id: string) => HTMLElement | null;
    optionalSelector: (selector: string) => Element | null;
    requiredElement: (id: string) => HTMLElement;
  };

  type ElementLookup<TIds extends Record<string, string>, TValue> = {
    [Key in keyof TIds]: TValue;
  };

  const requiredElementIds = {
    assistantDrawer: "assistant-drawer",
    activePreview: "active-preview",
    assistantChatPanel: "assistant-chat-panel",
    assistantInput: "assistant-input",
    assistantLog: "assistant-log",
    assistantSendButton: "assistant-send-button",
    assistantSelection: "assistant-selection",
    assistantSuggestions: "assistant-suggestions",
    assistantToggle: "assistant-toggle",
    apiExplorerBack: "api-explorer-back",
    apiExplorerActive: "api-explorer-active",
    apiExplorerCopy: "api-explorer-copy",
    apiExplorerForm: "api-explorer-form",
    apiExplorerResource: "api-explorer-resource",
    apiExplorerRoot: "api-explorer-root",
    apiExplorerSlide: "api-explorer-slide",
    apiExplorerStatus: "api-explorer-status",
    apiExplorerUrl: "api-explorer-url",
    captureVariantButton: "capture-variant-button",
    checkLlmButton: "check-llm-button",
    closeValidationPageButton: "close-validation-page",
    compareApplyButton: "compare-apply-button",
    compareApplyValidateButton: "compare-apply-validate-button",
    compareChangeSummary: "compare-change-summary",
    compareDecisionSupport: "compare-decision-support",
    compareEmpty: "compare-empty",
    compareHighlights: "compare-highlights",
    compareSourceGrid: "compare-source-grid",
    compareStats: "compare-stats",
    compareSummary: "compare-summary",
    currentSlidePanel: "current-slide-panel",
    debugDrawer: "debug-drawer",
    debugDrawerToggle: "debug-drawer-toggle",
    contentRunPreview: "content-run-preview",
    contentRunPreviewEyebrow: "content-run-preview-eyebrow",
    contentRunPreviewTitle: "content-run-preview-title",
    contentRunSummary: "content-run-summary",
    approvePresentationOutlineButton: "approve-presentation-outline-button",
    backToPresentationOutlineButton: "back-to-presentation-outline-button",
    createPresentationButton: "create-presentation-button",
    createSystemSlideButton: "create-system-slide-button",
    creationStageBrief: "creation-stage-brief",
    creationStageContent: "creation-stage-content",
    creationStageStructure: "creation-stage-structure",
    designMaxWords: "design-max-words",
    designMinCaptionGap: "design-min-caption-gap",
    designMinContentGap: "design-min-content-gap",
    designMinFontSize: "design-min-font-size",
    designMinPanelPadding: "design-min-panel-padding",
    deckStructureList: "deck-structure-list",
    deckStructureNote: "deck-structure-note",
    deleteSlideButton: "delete-slide-button",
    exitVariantReviewButton: "exit-variant-review-button",
    exportMenu: "export-menu",
    exportMenuButton: "export-menu-button",
    exportMenuPopover: "export-menu-popover",
    exportPdfButton: "export-pdf-button",
    generatePresentationOutlineButton: "generate-presentation-outline-button",
    generateOutlinePlanButton: "generate-outline-plan-button",
    ideateCandidateCount: "ideate-candidate-count",
    ideateDeckStructureButton: "ideate-deck-structure-button",
    ideateSlideButton: "ideate-slide-button",
    ideateStructureButton: "ideate-structure-button",
    ideateThemeButton: "ideate-theme-button",
    refineDeckNarrationButton: "refine-deck-narration-button",
    refineNarrationButton: "refine-narration-button",
    deckAudience: "deck-audience",
    deckAuthor: "deck-author",
    deckCompany: "deck-company",
    deckConstraints: "deck-constraints",
    deckLang: "deck-lang",
    deckLengthApplyButton: "deck-length-apply-button",
    deckLengthMode: "deck-length-mode",
    deckLengthModeHelp: "deck-length-mode-help",
    deckLengthPlanButton: "deck-length-plan-button",
    deckLengthPlanList: "deck-length-plan-list",
    deckLengthRestoreList: "deck-length-restore-list",
    deckLengthSummary: "deck-length-summary",
    deckLengthTarget: "deck-length-target",
    deckObjective: "deck-objective",
    deckOutline: "deck-outline",
    deckSubject: "deck-subject",
    deckThemeBrief: "deck-theme-brief",
    deckTitle: "deck-title",
    deckTone: "deck-tone",
    applyLayoutButton: "apply-layout-button",
    deleteFavoriteLayoutButton: "delete-favorite-layout-button",
    favoriteLayoutButton: "favorite-layout-button",
    fillMaterialButton: "fill-material-button",
    fitMaterialButton: "fit-material-button",
    copyLayoutJsonButton: "copy-layout-json-button",
    copyDeckLayoutPackButton: "copy-deck-layout-pack-button",
    copyFavoriteLayoutPackButton: "copy-favorite-layout-pack-button",
    importLayoutDeckButton: "import-layout-deck-button",
    importLayoutFavoriteButton: "import-layout-favorite-button",
    layoutLibraryDetails: "layout-library-details",
    layoutDrawer: "layout-drawer",
    layoutDrawerToggle: "layout-drawer-toggle",
    customLayoutDiscardButton: "custom-layout-discard-button",
    customLayoutCompactSpacingButton: "custom-layout-compact-spacing-button",
    customLayoutJson: "custom-layout-json",
    customLayoutLoadButton: "custom-layout-load-button",
    customLayoutLiveMap: "custom-layout-live-map",
    customLayoutLivePreview: "custom-layout-live-preview",
    customLayoutMinFont: "custom-layout-min-font",
    customLayoutMultiPreview: "custom-layout-multi-preview",
    customLayoutPreviewMapTab: "custom-layout-preview-map-tab",
    customLayoutPreviewButton: "custom-layout-preview-button",
    customLayoutPreviewSlideTab: "custom-layout-preview-slide-tab",
    customLayoutProfile: "custom-layout-profile",
    customLayoutSpacing: "custom-layout-spacing",
    customLayoutStatus: "custom-layout-status",
    customLayoutTreatment: "custom-layout-treatment",
    customLayoutValidation: "custom-layout-validation",
    customVisualContent: "custom-visual-content",
    customVisualDescription: "custom-visual-description",
    customVisualDetachButton: "detach-custom-visual-button",
    customVisualFile: "custom-visual-file",
    customVisualList: "custom-visual-list",
    customVisualRole: "custom-visual-role",
    customVisualSaveButton: "save-custom-visual-button",
    customVisualTitle: "custom-visual-title",
    layoutExchangeJson: "layout-exchange-json",
    layoutStudioList: "layout-studio-list",
    layoutStudioLoadSelectedButton: "layout-studio-load-selected-button",
    layoutStudioMap: "layout-studio-map",
    layoutStudioMinFont: "layout-studio-min-font",
    layoutStudioMultiPreview: "layout-studio-multi-preview",
    layoutStudioPreviewButton: "layout-studio-preview-button",
    layoutStudioProfile: "layout-studio-profile",
    layoutStudioSpacing: "layout-studio-spacing",
    layoutStudioStatus: "layout-studio-status",
    layoutStudioTreatment: "layout-studio-treatment",
    layoutLibrarySelect: "layout-library-select",
    layoutSaveName: "layout-save-name",
    llmStatusNote: "llm-status-note",
    llmNavStatus: "llm-nav-status",
    llmModelApplyButton: "apply-llm-model-button",
    llmModelClearButton: "clear-llm-model-button",
    llmModelControl: "llm-model-control",
    llmModelNote: "llm-model-note",
    llmModelRefreshButton: "refresh-llm-models-button",
    llmModelSelect: "llm-model-select",
    llmPopover: "llm-status-popover",
    manualSystemAfter: "manual-system-after",
    manualSystemDetour: "manual-system-detour",
    manualDeleteSlide: "manual-delete-slide",
    manualDeleteDetails: "manual-delete-details",
    manualDeleteReference: "manual-delete-reference",
    manualSystemReference: "manual-system-reference",
    manualSystemDetails: "manual-system-details",
    manualSystemMaterial: "manual-system-material",
    memoryCreateButton: "memory-create-button",
    memoryCreateForm: "memory-create-form",
    memoryDetail: "memory-detail",
    memoryDrawer: "memory-drawer",
    memoryDrawerToggle: "memory-drawer-toggle",
    memoryDependencyMap: "memory-dependency-map",
    memoryDerivedComparison: "memory-derived-comparison",
    memoryList: "memory-list",
    memoryPage: "memory-page",
    memoryRefreshButton: "memory-refresh-button",
    memorySearch: "memory-search",
    memoryStatus: "memory-status",
    memoryStatusNote: "memory-status-note",
    memorySummary: "memory-summary",
    memoryType: "memory-type",
    memoryWarningList: "memory-warning-list",
    memoryWorkbenchCount: "memory-workbench-count",
    memoryWorkbenchCreateButton: "memory-workbench-create-button",
    memoryWorkbenchCreateDetail: "memory-workbench-create-detail",
    memoryWorkbenchCreateForm: "memory-workbench-create-form",
    memoryWorkbenchCreateStatus: "memory-workbench-create-status",
    memoryWorkbenchCreateSummary: "memory-workbench-create-summary",
    memoryWorkbenchCreateType: "memory-workbench-create-type",
    memoryWorkbenchConfidenceFilter: "memory-workbench-confidence-filter",
    memoryWorkbenchDetail: "memory-workbench-detail",
    memoryWorkbenchEvidenceFilter: "memory-workbench-evidence-filter",
    memoryWorkbenchList: "memory-workbench-list",
    memoryWorkbenchRefreshButton: "memory-workbench-refresh-button",
    memoryWorkbenchRetireButton: "memory-workbench-retire-button",
    memoryWorkbenchSearch: "memory-workbench-search",
    memoryWorkbenchStatus: "memory-workbench-status",
    memoryWorkbenchStatusFilter: "memory-workbench-status-filter",
    memoryWorkbenchSummary: "memory-workbench-summary",
    memoryWorkbenchTypeFilter: "memory-workbench-type-filter",
    memoryWorkbenchUsageFilter: "memory-workbench-usage-filter",
    materialAlt: "material-alt",
    materialCaption: "material-caption",
    materialDetachButton: "detach-material-button",
    materialFile: "material-file",
    materialFocalPoint: "material-focal-point",
    materialList: "material-list",
    materialValidation: "material-validation",
    materialUploadButton: "upload-material-button",
    svglResults: "svgl-results",
    svglSearchButton: "svgl-search-button",
    svglSearchQuery: "svgl-search-query",
    manualSystemSummary: "manual-system-summary",
    manualSystemTitle: "manual-system-title",
    operationStatus: "operation-status",
    openManualDeleteButton: "open-manual-delete-button",
    openManualSystemButton: "open-manual-system-button",
    openSlideReorderButton: "open-slide-reorder-button",
    outlineDrawer: "outline-drawer",
    outlineDrawerToggle: "outline-drawer-toggle",
    outlinePlanDensity: "outline-plan-density",
    outlinePlanList: "outline-plan-list",
    outlinePlanTargetSlides: "outline-plan-target-slides",
    presentationAudience: "presentation-audience",
    presentationCreationStatus: "presentation-creation-status",
    presentationConstraints: "presentation-constraints",
    presentationDensity: "presentation-density",
    presentationFontFamily: "presentation-font-family",
    presentationOutlineList: "presentation-outline-list",
    presentationOutlineSourceUrls: "presentation-outline-source-urls",
    presentationOutlineSourceText: "presentation-outline-source-text",
    presentationOutlineSummary: "presentation-outline-summary",
    presentationOutlineTitle: "presentation-outline-title",
    presentationImageSearchProvider: "presentation-image-search-provider",
    presentationImageSearchQuery: "presentation-image-search-query",
    presentationImageSearchRestrictions: "presentation-image-search-restrictions",
    presentationList: "presentation-list",
    presentationMaterialFile: "presentation-material-file",
    presentationLanguage: "presentation-language",
    presentationObjective: "presentation-objective",
    presentationResultCount: "presentation-result-count",
    presentationSavedTheme: "presentation-saved-theme",
    presentationSearch: "presentation-search",
    presentationSourceEvidence: "presentation-source-evidence",
    presentationSourceOutline: "presentation-source-outline",
    presentationSourceUrls: "presentation-source-urls",
    presentationSourceText: "presentation-source-text",
    presentationSourcingStyle: "presentation-sourcing-style",
    presentationTargetSlides: "presentation-target-slides",
    presentationThemeAccent: "presentation-theme-accent",
    presentationThemeBg: "presentation-theme-bg",
    presentationThemeBrief: "presentation-theme-brief",
    presentationThemeName: "presentation-theme-name",
    presentationThemePanel: "presentation-theme-panel",
    presentationThemePrimary: "presentation-theme-primary",
    presentationThemePreview: "presentation-theme-preview",
    presentationThemeReview: "presentation-theme-review",
    presentationThemeSecondary: "presentation-theme-secondary",
    presentationThemeVariantList: "presentation-theme-variant-list",
    presentationTitle: "presentation-title",
    presentationTone: "presentation-tone",
    presentationsPage: "presentations-page",
    reportBox: "report-box",
    redoLayoutButton: "redo-layout-button",
    quickCustomLayoutButton: "quick-custom-layout-button",
    quickCustomLayoutProfile: "quick-custom-layout-profile",
    regenerateSlideButton: "regenerate-slide-button",
    regeneratePresentationOutlineButton: "regenerate-presentation-outline-button",
    regeneratePresentationOutlineWithSourcesButton: "regenerate-presentation-outline-with-sources-button",
    recenterMaterialButton: "recenter-material-button",
    saveDeckContextButton: "save-deck-context-button",
    saveLayoutButton: "save-layout-button",
    saveDeckThemeButton: "save-deck-theme-button",
    openPresentationModeButton: "open-presentation-mode-button",
    saveValidationSettingsButton: "save-validation-settings-button",
    saveSlideContextButton: "save-slide-context-button",
    applySlideReorderButton: "apply-slide-reorder-button",
    cancelSlideReorderButton: "cancel-slide-reorder-button",
    saveSlideSpecButton: "save-slide-spec-button",
    showPresentationsPageButton: "show-presentations-page",
    showStudioPageButton: "show-studio-page",
    showMemoryPageButton: "show-memory-page",
    showLlmDiagnosticsButton: "show-llm-diagnostics",
    sourceList: "source-list",
    sourceText: "source-text",
    sourceTitle: "source-title",
    sourceUrl: "source-url",
    addSourceButton: "add-source-button",
    themeToggle: "theme-toggle",
    themeToggleLabel: "theme-toggle-label",
    contextDrawer: "context-drawer",
    contextDrawerToggle: "context-drawer-toggle",
    themeDrawer: "theme-drawer",
    themeDrawerToggle: "theme-drawer-toggle",
    themeBrief: "theme-brief",
    themeColorScheme: "theme-color-scheme",
    themeFavoriteList: "theme-favorite-list",
    generateThemeFromBriefButton: "generate-theme-from-brief-button",
    generateThemeCandidatesButton: "generate-theme-candidates-button",
    slideSpecEditor: "slide-spec-editor",
    slideSpecStatus: "slide-spec-status",
    selectedSlideLabel: "selected-slide-label",
    slideIntent: "slide-intent",
    slideLayoutHint: "slide-layout-hint",
    slideMustInclude: "slide-must-include",
    slideNotes: "slide-notes",
    slideTitle: "slide-title",
    slideValue: "slide-value",
    slideReorderDialog: "slide-reorder-dialog",
    slideReorderList: "slide-reorder-list",
    slideSpecHighlight: "slide-spec-highlight",
    showValidationPageButton: "show-validation-page",
    studioPage: "studio-page",
    structuredDraftDrawer: "structured-draft-drawer",
    structuredDraftToggle: "structured-draft-toggle",
    thumbRail: "thumb-rail",
    themeAccent: "theme-accent",
    themeBg: "theme-bg",
    themeFontFamily: "theme-font-family",
    themeLight: "theme-light",
    themeMuted: "theme-muted",
    themePanel: "theme-panel",
    themePrimary: "theme-primary",
    themeProgressFill: "theme-progress-fill",
    themeProgressTrack: "theme-progress-track",
    themeSecondary: "theme-secondary",
    themeSurface: "theme-surface",
    validationMediaMode: "validation-media-mode",
    validationPage: "validation-page",
    validationSummary: "validation-summary",
    exportPptxButton: "export-pptx-button",
    validateButton: "validate-button",
    validateRenderButton: "validate-render-button",
    validationStatus: "validation-status",
    variantGenerationPanel: "variant-generation-panel",
    variantFlow: "variant-flow",
    variantLabel: "variant-label",
    variantList: "variant-list",
    variantReviewWorkspace: "variant-review-workspace",
    variantStorageNote: "variant-storage-note",
    workflowCompare: "workflow-compare",
    workflowHistory: "workflow-history"
  } as const;

  const optionalElementIds = {
    contentRunPreviewActions: "content-run-preview-actions",
    contentRunNavStatus: "content-run-nav-status",
    manualSystemType: "manual-system-type",
    savePresentationThemeButton: "save-presentation-theme-button",
    openCreatedPresentationButton: "open-created-presentation-button",
    sourceRetrievalList: "source-retrieval-list",
    sourceRetrievalSummary: "source-retrieval-summary",
    promptBudgetList: "prompt-budget-list",
    promptBudgetSummary: "prompt-budget-summary",
    studioContentRunPanel: "studio-content-run-panel"
  } as const;

  const optionalSelectorIds = {
    presentationCreateDetails: ".presentation-create-details"
  } as const;

  export type Elements = ReturnType<typeof createElements>;

  function mapElements<TIds extends Record<string, string>, TValue>(
    ids: TIds,
    lookup: (id: string) => TValue
  ): ElementLookup<TIds, TValue> {
    return Object.fromEntries(
      Object.entries(ids).map(([key, id]) => [key, lookup(id)])
    ) as ElementLookup<TIds, TValue>;
  }

  export function createElements(core: ElementCore = StudioClientCore) {
    const optionalElement = (id: string) => core.optionalElement(id) as StudioElement | null;
    const optionalSelector = (selector: string) => core.optionalSelector(selector) as StudioElement | null;
    const requiredElement = (id: string) => core.requiredElement(id) as StudioElement;

    return {
      ...mapElements(requiredElementIds, requiredElement),
      ...mapElements(optionalElementIds, optionalElement),
      ...mapElements(optionalSelectorIds, optionalSelector)
    };
  }
}
