import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import ts from "typescript";

const rootDir = path.resolve(import.meta.dirname, "..");
const distDir = path.join(rootDir, "dist");

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    stdio: "inherit"
  });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed`);
  }
}

function copyPath(source, target, options = {}) {
  if (!fs.existsSync(source)) {
    return;
  }

  fs.cpSync(source, target, {
    dereference: false,
    filter: options.filter,
    force: true,
    recursive: true
  });
}

function rewriteRuntimeImports(source) {
  return source.replace(/require\((["'])([^"']+)\.ts\1\)/g, "require($1$2.js$1)");
}

function transpileTypeScript(source, target, compilerOptions) {
  const output = ts.transpileModule(fs.readFileSync(source, "utf8"), {
    compilerOptions,
    fileName: source
  }).outputText;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, rewriteRuntimeImports(output), "utf8");
}

function transpileTree(sourceDir, targetDir, compilerOptions) {
  if (!fs.existsSync(sourceDir)) {
    return;
  }

  for (const entry of fs.readdirSync(sourceDir, { withFileTypes: true })) {
    const source = path.join(sourceDir, entry.name);
    const target = path.join(targetDir, entry.name);
    if (entry.isDirectory()) {
      transpileTree(source, target, compilerOptions);
      continue;
    }

    if (entry.isFile() && path.extname(entry.name) === ".ts") {
      transpileTypeScript(source, `${target.slice(0, -3)}.js`, compilerOptions);
    }
  }
}

function copyJson(source, target, transform) {
  const value = JSON.parse(fs.readFileSync(source, "utf8"));
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, `${JSON.stringify(transform(value), null, 2)}\n`, "utf8");
}

run("npm", ["run", "studio:client:build"]);

fs.rmSync(distDir, { force: true, recursive: true });
fs.mkdirSync(distDir, { recursive: true });

copyPath(path.join(rootDir, "bin"), path.join(distDir, "bin"), {
  filter: (source) => path.extname(source) !== ".ts"
});
copyPath(path.join(rootDir, "studio", "client-dist"), path.join(distDir, "studio", "client-dist"));
copyPath(path.join(rootDir, "studio", "client", "styles.css"), path.join(distDir, "studio", "client", "styles.css"));
copyPath(path.join(rootDir, "studio", "server"), path.join(distDir, "studio", "server"), {
  filter: (source) => path.extname(source) !== ".ts"
});
copyPath(path.join(rootDir, "presentations", "slideotter"), path.join(distDir, "presentations", "slideotter"));
copyPath(path.join(rootDir, "slides", "assets"), path.join(distDir, "slides", "assets"));

transpileTypeScript(path.join(rootDir, "studio", "client", "slide-dom.ts"), path.join(distDir, "studio", "client", "slide-dom.js"), {
  module: ts.ModuleKind.None,
  target: ts.ScriptTarget.ES2022
});
transpileTree(path.join(rootDir, "studio", "server"), path.join(distDir, "studio", "server"), {
  module: ts.ModuleKind.CommonJS,
  target: ts.ScriptTarget.ES2022
});

const binFile = path.join(distDir, "bin", "slideotter.mjs");
if (fs.existsSync(binFile)) {
  fs.writeFileSync(binFile, rewriteRuntimeImports(fs.readFileSync(binFile, "utf8")), "utf8");
}

copyJson(path.join(rootDir, "package.json"), path.join(distDir, "package.json"), (packageJson) => ({
  name: packageJson.name,
  version: packageJson.version,
  description: packageJson.description,
  type: packageJson.type,
  bin: {
    slideotter: "./bin/slideotter.mjs"
  },
  dependencies: packageJson.dependencies || {},
  engines: packageJson.engines || {
    node: ">=24"
  }
}));

fs.writeFileSync(path.join(distDir, "README.md"), [
  "# slideotter",
  "",
  "This directory is generated by `npm run package:build` and is the packaged runtime surface.",
  "Use the top-level package tarball or `slideotter` command rather than editing files here.",
  ""
].join("\n"), "utf8");

process.stdout.write(`Built package runtime in ${path.relative(rootDir, distDir)}\n`);
