export function renderPresentationScript(): string {
  return [
    "(function () {",
    "  const slideNodes = Array.from(document.querySelectorAll('.dom-presentation-document__slides > .dom-slide'));",
    "  const pageNode = document.querySelector('.dom-presentation-document__page');",
    "  const stageNode = document.querySelector('.dom-presentation-document__slides');",
    "  if (!slideNodes.length) {",
    "    return;",
    "  }",
    "",
    "  function clamp(value, min, max) {",
    "    return Math.min(Math.max(value, min), max);",
    "  }",
    "",
    "  function slideCoordinate(slideNode, fallbackIndex) {",
    "    const x = Number.parseInt(slideNode.getAttribute('data-presentation-x') || '', 10);",
    "    const y = Number.parseInt(slideNode.getAttribute('data-presentation-y') || '', 10);",
    "    return {",
    "      index: fallbackIndex,",
    "      node: slideNode,",
    "      x: Number.isFinite(x) && x > 0 ? x : fallbackIndex,",
    "      y: Number.isFinite(y) && y >= 0 ? y : 0",
    "    };",
    "  }",
    "",
    "  const coordinates = slideNodes.map((slideNode, index) => slideCoordinate(slideNode, index + 1));",
    "  const coreCoordinates = coordinates.filter((coordinate) => coordinate.y === 0);",
    "  const maxX = coreCoordinates.length ? Math.max.apply(null, coreCoordinates.map((coordinate) => coordinate.x)) : slideNodes.length;",
    "",
    "  function readCoordinateFromHash() {",
    "    const hash = String(window.location.hash || '');",
    "    const xMatch = hash.match(/x=(\\d+)/);",
    "    const yMatch = hash.match(/y=(\\d+)/);",
    "    const parsedX = xMatch ? Number.parseInt(xMatch[1], 10) : 1;",
    "    const parsedY = yMatch ? Number.parseInt(yMatch[1], 10) : 0;",
    "    return {",
    "      x: Number.isFinite(parsedX) ? clamp(parsedX, 1, maxX) : 1,",
    "      y: Number.isFinite(parsedY) ? Math.max(0, parsedY) : 0",
    "    };",
    "  }",
    "",
    "  function findCoordinate(x, y) {",
    "    return coordinates.find((coordinate) => coordinate.x === x && coordinate.y === y)",
    "      || coordinates.find((coordinate) => coordinate.x === x && coordinate.y === 0)",
    "      || coordinates[0];",
    "  }",
    "",
    "  function maxYForX(x) {",
    "    const stack = coordinates.filter((coordinate) => coordinate.x === x);",
    "    return stack.length ? Math.max.apply(null, stack.map((coordinate) => coordinate.y)) : 0;",
    "  }",
    "",
    "  function writeHash(coordinate) {",
    "    const nextHash = coordinate.y > 0 ? '#x=' + coordinate.x + ',y=' + coordinate.y : '#x=' + coordinate.x;",
    "    if (window.location.hash !== nextHash) {",
    "      window.history.replaceState(null, '', nextHash);",
    "    }",
    "  }",
    "",
    "  function syncScale() {",
    "    const viewport = window.visualViewport;",
    "    const viewportWidth = viewport && viewport.width > 0 ? viewport.width : window.innerWidth;",
    "    const viewportHeight = viewport && viewport.height > 0 ? viewport.height : window.innerHeight;",
    "    const viewportLeft = viewport ? viewport.offsetLeft : 0;",
    "    const viewportTop = viewport ? viewport.offsetTop : 0;",
    "    const scale = Math.min(viewportWidth / 960, viewportHeight / 540);",
    "    const safeScale = scale > 0 ? scale : 1;",
    "    if (pageNode instanceof HTMLElement) {",
    "      pageNode.style.inset = 'auto';",
    "      pageNode.style.left = viewportLeft + 'px';",
    "      pageNode.style.top = viewportTop + 'px';",
    "      pageNode.style.width = viewportWidth + 'px';",
    "      pageNode.style.height = viewportHeight + 'px';",
    "    }",
    "    if (stageNode instanceof HTMLElement) {",
    "      stageNode.style.width = (960 * safeScale) + 'px';",
    "      stageNode.style.height = (540 * safeScale) + 'px';",
    "      stageNode.style.setProperty('--presentation-scale', String(safeScale));",
    "    }",
    "    slideNodes.forEach((slideNode) => {",
    "      if (slideNode instanceof HTMLElement) {",
    "        slideNode.style.transform = 'scale(' + safeScale + ')';",
    "      }",
    "    });",
    "  }",
    "",
    "  function render(coordinate) {",
    "    const activeCoordinate = findCoordinate(coordinate.x, coordinate.y);",
    "    slideNodes.forEach((slideNode, slideOffset) => {",
    "      const isActive = slideOffset === activeCoordinate.index - 1;",
    "      slideNode.hidden = !isActive;",
    "      slideNode.classList.toggle('is-active', isActive);",
    "      slideNode.setAttribute('aria-hidden', isActive ? 'false' : 'true');",
    "    });",
    "    document.body.dataset.presentationIndex = String(activeCoordinate.x);",
    "    document.body.dataset.presentationY = String(activeCoordinate.y);",
    "    document.body.dataset.presentationSlideIndex = String(activeCoordinate.index);",
    "    document.body.dataset.presentationDetourUp = activeCoordinate.y > 0 ? 'true' : 'false';",
    "    document.body.dataset.presentationDetourDown = activeCoordinate.y < maxYForX(activeCoordinate.x) ? 'true' : 'false';",
    "    writeHash(activeCoordinate);",
    "  }",
    "",
    "  function renderHash() {",
    "    render(readCoordinateFromHash());",
    "  }",
    "",
    "  function moveHorizontal(delta) {",
    "    const coordinate = readCoordinateFromHash();",
    "    const nextX = ((coordinate.x - 1 + delta + maxX) % maxX) + 1;",
    "    render({ x: nextX, y: 0 });",
    "  }",
    "",
    "  function moveVertical(delta) {",
    "    const coordinate = readCoordinateFromHash();",
    "    render({ x: coordinate.x, y: clamp(coordinate.y + delta, 0, maxYForX(coordinate.x)) });",
    "  }",
    "",
    "  function exitPresentationMode() {",
    "    if (window.opener && !window.opener.closed) {",
    "      window.close();",
    "      if (window.closed) {",
    "        return;",
    "      }",
    "    }",
    "",
    "    const studioUrl = new URL('/', window.location.href);",
    "    studioUrl.hash = '#studio';",
    "    window.location.assign(studioUrl.toString());",
    "  }",
    "",
    "  window.addEventListener('keydown', (event) => {",
    "    if (event.defaultPrevented || event.metaKey || event.ctrlKey || event.altKey) {",
    "      return;",
    "    }",
    "",
    "    switch (event.key) {",
    "      case 'ArrowRight':",
    "      case 'PageDown':",
    "      case ' ':",
    "        event.preventDefault();",
    "        moveHorizontal(1);",
    "        break;",
    "      case 'ArrowLeft':",
    "      case 'PageUp':",
    "        event.preventDefault();",
    "        moveHorizontal(-1);",
    "        break;",
    "      case 'ArrowDown':",
    "        event.preventDefault();",
    "        moveVertical(1);",
    "        break;",
    "      case 'ArrowUp':",
    "        event.preventDefault();",
    "        moveVertical(-1);",
    "        break;",
    "      case 'Home':",
    "        event.preventDefault();",
    "        render({ x: 1, y: 0 });",
    "        break;",
    "      case 'End':",
    "        event.preventDefault();",
    "        render({ x: maxX, y: 0 });",
    "        break;",
    "      case 'Escape':",
    "        event.preventDefault();",
    "        exitPresentationMode();",
    "        break;",
    "      default:",
    "        break;",
    "    }",
    "  });",
    "",
    "  window.addEventListener('hashchange', function () {",
    "    renderHash();",
    "  });",
    "  window.addEventListener('resize', syncScale);",
    "  if (window.visualViewport) {",
    "    window.visualViewport.addEventListener('resize', syncScale);",
    "    window.visualViewport.addEventListener('scroll', syncScale);",
    "  }",
    "  syncScale();",
    "  renderHash();",
    "})();"
  ].join("\n");
}
