export function renderPresentationScript(): string {
  return [
    "(function () {",
    "  const slideNodes = Array.from(document.querySelectorAll('.dom-presentation-document__slides > .dom-slide'));",
    "  const pageNode = document.querySelector('.dom-presentation-document__page');",
    "  const stageNode = document.querySelector('.dom-presentation-document__slides');",
    "  const narrationPanel = document.querySelector('.dom-presentation-narration');",
    "  const narrationStatus = document.querySelector('[data-narration-status]');",
    "  const narrationScript = document.querySelector('.dom-presentation-narration [data-narration-script]');",
    "  const narrationAutoAdvance = document.querySelector('[data-narration-auto-advance]');",
    "  const narrationBody = document.querySelector('[data-narration-body]');",
    "  const narrationToggle = document.querySelector('[data-narration-action=\"toggle\"]');",
    "  const narrationVoice = document.querySelector('[data-narration-voice]');",
    "  const narrationAudio = new Audio();",
    "  let activeNarrationMode = 'none';",
    "  if (!slideNodes.length) {",
    "    return;",
    "  }",
    "",
    "  function clamp(value, min, max) {",
    "    return Math.min(Math.max(value, min), max);",
    "  }",
    "",
    "  function slideCoordinate(slideNode, fallbackIndex) {",
    "    const x = Number.parseInt(slideNode.getAttribute('data-presentation-x') || '', 10);",
    "    const y = Number.parseInt(slideNode.getAttribute('data-presentation-y') || '', 10);",
    "    return {",
    "      index: fallbackIndex,",
    "      node: slideNode,",
    "      x: Number.isFinite(x) && x > 0 ? x : fallbackIndex,",
    "      y: Number.isFinite(y) && y >= 0 ? y : 0",
    "    };",
    "  }",
    "",
    "  const coordinates = slideNodes.map((slideNode, index) => slideCoordinate(slideNode, index + 1));",
    "  const coreCoordinates = coordinates.filter((coordinate) => coordinate.y === 0);",
    "  const maxX = coreCoordinates.length ? Math.max.apply(null, coreCoordinates.map((coordinate) => coordinate.x)) : slideNodes.length;",
    "",
    "  function readCoordinateFromHash() {",
    "    const hash = String(window.location.hash || '');",
    "    const xMatch = hash.match(/x=(\\d+)/);",
    "    const yMatch = hash.match(/y=(\\d+)/);",
    "    const parsedX = xMatch ? Number.parseInt(xMatch[1], 10) : 1;",
    "    const parsedY = yMatch ? Number.parseInt(yMatch[1], 10) : 0;",
    "    return {",
    "      x: Number.isFinite(parsedX) ? clamp(parsedX, 1, maxX) : 1,",
    "      y: Number.isFinite(parsedY) ? Math.max(0, parsedY) : 0",
    "    };",
    "  }",
    "",
    "  function findCoordinate(x, y) {",
    "    return coordinates.find((coordinate) => coordinate.x === x && coordinate.y === y)",
    "      || coordinates.find((coordinate) => coordinate.x === x && coordinate.y === 0)",
    "      || coordinates[0];",
    "  }",
    "",
    "  function activeCoordinate() {",
    "    const coordinate = readCoordinateFromHash();",
    "    return findCoordinate(coordinate.x, coordinate.y);",
    "  }",
    "",
    "  function maxYForX(x) {",
    "    const stack = coordinates.filter((coordinate) => coordinate.x === x);",
    "    return stack.length ? Math.max.apply(null, stack.map((coordinate) => coordinate.y)) : 0;",
    "  }",
    "",
    "  function writeHash(coordinate) {",
    "    const nextHash = coordinate.y > 0 ? '#x=' + coordinate.x + ',y=' + coordinate.y : '#x=' + coordinate.x;",
    "    if (window.location.hash !== nextHash) {",
    "      window.history.replaceState(null, '', nextHash);",
    "    }",
    "  }",
    "",
    "  function narrationTextFor(coordinate) {",
    "    return String(coordinate && coordinate.node && coordinate.node.getAttribute('data-narration-script') || '').trim();",
    "  }",
    "",
    "  function narrationAdvanceFor(coordinate) {",
    "    return String(coordinate && coordinate.node && coordinate.node.getAttribute('data-narration-advance') || 'manual').trim();",
    "  }",
    "",
    "  function narrationSlideIdFor(coordinate) {",
    "    return String(coordinate && coordinate.node && coordinate.node.getAttribute('data-slide-id') || 'slide-' + (coordinate && coordinate.index || 1)).trim();",
    "  }",
    "",
    "  function presentationId() {",
    "    const explicit = String(document.body && document.body.getAttribute('data-presentation-id') || '').trim();",
    "    if (explicit) {",
    "      return explicit;",
    "    }",
    "    const match = String(window.location.pathname || '').match(/\\/present\\/([a-z0-9-]+)/);",
    "    return match ? match[1] : 'active';",
    "  }",
    "",
    "  function setNarrationStatus(message) {",
    "    if (narrationStatus) {",
    "      narrationStatus.textContent = message;",
    "    }",
    "  }",
    "",
    "  function setNarrationCollapsed(collapsed) {",
    "    if (narrationPanel) {",
    "      narrationPanel.dataset.narrationCollapsed = collapsed ? 'true' : 'false';",
    "    }",
    "    if (narrationBody) {",
    "      narrationBody.hidden = collapsed;",
    "    }",
    "    if (narrationToggle) {",
    "      narrationToggle.setAttribute('aria-expanded', collapsed ? 'false' : 'true');",
    "      narrationToggle.textContent = collapsed ? 'Show' : 'Minimize';",
    "    }",
    "    try {",
    "      window.sessionStorage.setItem('slideotter:narration-collapsed', collapsed ? 'true' : 'false');",
    "    } catch (error) {",
    "      // Session storage can be unavailable in constrained browser contexts.",
    "    }",
    "  }",
    "",
    "  function toggleNarrationCollapsed() {",
    "    const collapsed = narrationPanel && narrationPanel.dataset.narrationCollapsed === 'true';",
    "    setNarrationCollapsed(!collapsed);",
    "  }",
    "",
    "  function syncNarrationReview(coordinate) {",
    "    const text = narrationTextFor(coordinate);",
    "    if (narrationScript) {",
    "      narrationScript.textContent = text || 'No narration script for this slide.';",
    "    }",
    "    if (narrationPanel) {",
    "      narrationPanel.dataset.narrationAvailable = text ? 'true' : 'false';",
    "    }",
    "  }",
    "",
    "  function speechAvailable() {",
    "    return typeof window.speechSynthesis !== 'undefined' && typeof window.SpeechSynthesisUtterance !== 'undefined';",
    "  }",
    "",
    "  function voiceKey(voice) {",
    "    return String(voice && (voice.voiceURI || (voice.name + '|' + voice.lang)) || '');",
    "  }",
    "",
    "  function narrationVoices() {",
    "    if (!speechAvailable() || typeof window.speechSynthesis.getVoices !== 'function') {",
    "      return [];",
    "    }",
    "    return window.speechSynthesis.getVoices();",
    "  }",
    "",
    "  function selectedNarrationVoice() {",
    "    if (!narrationVoice) {",
    "      return null;",
    "    }",
    "    const selectedKey = String(narrationVoice.value || '');",
    "    if (!selectedKey) {",
    "      return null;",
    "    }",
    "    return narrationVoices().find(function (voice) {",
    "      return voiceKey(voice) === selectedKey;",
    "    }) || null;",
    "  }",
    "",
    "  function populateNarrationVoices() {",
    "    if (!narrationVoice) {",
    "      return;",
    "    }",
    "    const voices = narrationVoices();",
    "    let storedVoice = '';",
    "    try {",
    "      storedVoice = window.sessionStorage.getItem('slideotter:narration-voice') || '';",
    "    } catch (error) {",
    "      storedVoice = '';",
    "    }",
    "    const selectedKey = String(narrationVoice.value || storedVoice || '');",
    "    while (narrationVoice.firstChild) {",
    "      narrationVoice.removeChild(narrationVoice.firstChild);",
    "    }",
    "    const defaultOption = document.createElement('option');",
    "    defaultOption.value = '';",
    "    defaultOption.textContent = 'Default voice';",
    "    narrationVoice.appendChild(defaultOption);",
    "    voices.forEach(function (voice) {",
    "      const option = document.createElement('option');",
    "      option.value = voiceKey(voice);",
    "      option.textContent = voice.name + (voice.lang ? ' (' + voice.lang + ')' : '') + (voice.default ? ' - default' : '');",
    "      narrationVoice.appendChild(option);",
    "    });",
    "    if (voices.some(function (voice) { return voiceKey(voice) === selectedKey; })) {",
    "      narrationVoice.value = selectedKey;",
    "    } else {",
    "      narrationVoice.value = '';",
    "    }",
    "  }",
    "",
    "  function cancelNarration() {",
    "    narrationAudio.pause();",
    "    narrationAudio.removeAttribute('src');",
    "    narrationAudio.load();",
    "    if (speechAvailable()) {",
    "      window.speechSynthesis.cancel();",
    "    }",
    "    activeNarrationMode = 'none';",
    "    document.body.dataset.presentationNarrating = 'false';",
    "  }",
    "",
    "  function autoAdvanceEnabled() {",
    "    return Boolean(narrationAutoAdvance && narrationAutoAdvance.checked);",
    "  }",
    "",
    "  function advanceAfterNarration(coordinate) {",
    "    if (!autoAdvanceEnabled() || narrationAdvanceFor(coordinate) === 'manual') {",
    "      setNarrationStatus('Narration finished.');",
    "      return;",
    "    }",
    "    if (coordinate.y < maxYForX(coordinate.x)) {",
    "      render({ x: coordinate.x, y: coordinate.y + 1 });",
    "    } else if (coordinate.x < maxX) {",
    "      render({ x: coordinate.x + 1, y: 0 });",
    "    } else {",
    "      setNarrationStatus('Narration finished.');",
    "      return;",
    "    }",
    "    window.setTimeout(function () {",
    "      playNarration();",
    "    }, 260);",
    "  }",
    "",
    "  function playSpeechNarration(coordinate, text) {",
    "    if (!speechAvailable()) {",
    "      setNarrationStatus('Speech synthesis is not available in this browser.');",
    "      return;",
    "    }",
    "    cancelNarration();",
    "    const utterance = new window.SpeechSynthesisUtterance(text);",
    "    const voice = selectedNarrationVoice();",
    "    if (voice) {",
    "      utterance.voice = voice;",
    "    }",
    "    utterance.rate = 0.92;",
    "    utterance.pitch = 1;",
    "    utterance.volume = 1;",
    "    utterance.onstart = function () {",
    "      activeNarrationMode = 'speech';",
    "      document.body.dataset.presentationNarrating = 'true';",
    "      setNarrationStatus('Speaking slide ' + coordinate.index + '.');",
    "    };",
    "    utterance.onerror = function () {",
    "      activeNarrationMode = 'none';",
    "      document.body.dataset.presentationNarrating = 'false';",
    "      setNarrationStatus('Narration failed. Use manual controls.');",
    "    };",
    "    utterance.onend = function () {",
    "      activeNarrationMode = 'none';",
    "      document.body.dataset.presentationNarrating = 'false';",
    "      advanceAfterNarration(coordinate);",
    "    };",
    "    window.speechSynthesis.speak(utterance);",
    "  }",
    "",
    "  function playAudioNarration(coordinate, audioUrl, provider) {",
    "    cancelNarration();",
    "    activeNarrationMode = 'audio';",
    "    narrationAudio.src = audioUrl;",
    "    narrationAudio.onplay = function () {",
    "      document.body.dataset.presentationNarrating = 'true';",
    "      setNarrationStatus((provider === 'piper' ? 'Playing Piper narration for' : 'Playing narration for') + ' slide ' + coordinate.index + '.');",
    "    };",
    "    narrationAudio.onerror = function () {",
    "      activeNarrationMode = 'none';",
    "      document.body.dataset.presentationNarrating = 'false';",
    "      setNarrationStatus('Local narration audio failed. Trying browser voice.');",
    "      playSpeechNarration(coordinate, narrationTextFor(coordinate));",
    "    };",
    "    narrationAudio.onended = function () {",
    "      activeNarrationMode = 'none';",
    "      document.body.dataset.presentationNarrating = 'false';",
    "      advanceAfterNarration(coordinate);",
    "    };",
    "    narrationAudio.play().catch(function () {",
    "      activeNarrationMode = 'none';",
    "      document.body.dataset.presentationNarrating = 'false';",
    "      setNarrationStatus('Local narration playback was blocked. Trying browser voice.');",
    "      playSpeechNarration(coordinate, narrationTextFor(coordinate));",
    "    });",
    "  }",
    "",
    "  function requestLocalNarration(coordinate, text) {",
    "    return window.fetch('/api/v1/narration/synthesize', {",
    "      body: JSON.stringify({",
    "        presentationId: presentationId(),",
    "        slideId: narrationSlideIdFor(coordinate),",
    "        text: text",
    "      }),",
    "      headers: { 'Content-Type': 'application/json' },",
    "      method: 'POST'",
    "    }).then(function (response) {",
    "      if (!response.ok) {",
    "        throw new Error('Local narration unavailable.');",
    "      }",
    "      return response.json();",
    "    }).then(function (payload) {",
    "      return payload && payload.result && payload.result.audioUrl ? payload.result : null;",
    "    });",
    "  }",
    "",
    "  function playNarration() {",
    "    const coordinate = activeCoordinate();",
    "    const text = narrationTextFor(coordinate);",
    "    syncNarrationReview(coordinate);",
    "    if (!text) {",
    "      setNarrationStatus('No narration script for this slide.');",
    "      return;",
    "    }",
    "    setNarrationStatus('Preparing narration for slide ' + coordinate.index + '.');",
    "    requestLocalNarration(coordinate, text).then(function (result) {",
    "      if (result && result.audioUrl) {",
    "        playAudioNarration(coordinate, result.audioUrl, result.provider);",
    "        return;",
    "      }",
    "      playSpeechNarration(coordinate, text);",
    "    }).catch(function () {",
    "      playSpeechNarration(coordinate, text);",
    "    });",
    "  }",
    "",
    "  function pauseNarration() {",
    "    if (activeNarrationMode === 'audio') {",
    "      if (narrationAudio.paused) {",
    "        narrationAudio.play().then(function () {",
    "          setNarrationStatus('Narration resumed.');",
    "        }).catch(function () {",
    "          setNarrationStatus('Narration resume failed.');",
    "        });",
    "        return;",
    "      }",
    "      narrationAudio.pause();",
    "      setNarrationStatus('Narration paused.');",
    "      return;",
    "    }",
    "    if (!speechAvailable()) { return; }",
    "    if (window.speechSynthesis.paused) {",
    "      window.speechSynthesis.resume();",
    "      setNarrationStatus('Speaking resumed.');",
    "      return;",
    "    }",
    "    window.speechSynthesis.pause();",
    "    setNarrationStatus('Narration paused.');",
    "  }",
    "",
    "  function syncScale() {",
    "    const viewport = window.visualViewport;",
    "    const viewportWidth = viewport && viewport.width > 0 ? viewport.width : window.innerWidth;",
    "    const viewportHeight = viewport && viewport.height > 0 ? viewport.height : window.innerHeight;",
    "    const viewportLeft = viewport ? viewport.offsetLeft : 0;",
    "    const viewportTop = viewport ? viewport.offsetTop : 0;",
    "    const scale = Math.min(viewportWidth / 960, viewportHeight / 540);",
    "    const safeScale = scale > 0 ? scale : 1;",
    "    if (pageNode instanceof HTMLElement) {",
    "      pageNode.style.inset = 'auto';",
    "      pageNode.style.left = viewportLeft + 'px';",
    "      pageNode.style.top = viewportTop + 'px';",
    "      pageNode.style.width = viewportWidth + 'px';",
    "      pageNode.style.height = viewportHeight + 'px';",
    "    }",
    "    if (stageNode instanceof HTMLElement) {",
    "      stageNode.style.width = (960 * safeScale) + 'px';",
    "      stageNode.style.height = (540 * safeScale) + 'px';",
    "      stageNode.style.setProperty('--presentation-scale', String(safeScale));",
    "    }",
    "    slideNodes.forEach((slideNode) => {",
    "      if (slideNode instanceof HTMLElement) {",
    "        slideNode.style.transform = 'scale(' + safeScale + ')';",
    "      }",
    "    });",
    "  }",
    "",
    "  function render(coordinate) {",
    "    const activeCoordinate = findCoordinate(coordinate.x, coordinate.y);",
    "    slideNodes.forEach((slideNode, slideOffset) => {",
    "      const isActive = slideOffset === activeCoordinate.index - 1;",
    "      slideNode.hidden = !isActive;",
    "      slideNode.classList.toggle('is-active', isActive);",
    "      slideNode.setAttribute('aria-hidden', isActive ? 'false' : 'true');",
    "    });",
    "    document.body.dataset.presentationIndex = String(activeCoordinate.x);",
    "    document.body.dataset.presentationY = String(activeCoordinate.y);",
    "    document.body.dataset.presentationSlideIndex = String(activeCoordinate.index);",
    "    document.body.dataset.presentationDetourUp = activeCoordinate.y > 0 ? 'true' : 'false';",
    "    document.body.dataset.presentationDetourDown = activeCoordinate.y < maxYForX(activeCoordinate.x) ? 'true' : 'false';",
    "    syncNarrationReview(activeCoordinate);",
    "    writeHash(activeCoordinate);",
    "  }",
    "",
    "  function renderHash() {",
    "    render(readCoordinateFromHash());",
    "  }",
    "",
    "  function moveHorizontal(delta) {",
    "    cancelNarration();",
    "    const coordinate = readCoordinateFromHash();",
    "    const nextX = ((coordinate.x - 1 + delta + maxX) % maxX) + 1;",
    "    render({ x: nextX, y: 0 });",
    "  }",
    "",
    "  function moveVertical(delta) {",
    "    cancelNarration();",
    "    const coordinate = readCoordinateFromHash();",
    "    render({ x: coordinate.x, y: clamp(coordinate.y + delta, 0, maxYForX(coordinate.x)) });",
    "  }",
    "",
    "  function exitPresentationMode() {",
    "    cancelNarration();",
    "    if (window.opener && !window.opener.closed) {",
    "      window.close();",
    "      if (window.closed) {",
    "        return;",
    "      }",
    "    }",
    "",
    "    const studioUrl = new URL('/', window.location.href);",
    "    studioUrl.hash = '#studio';",
    "    window.location.assign(studioUrl.toString());",
    "  }",
    "",
    "  window.addEventListener('keydown', (event) => {",
    "    if (event.defaultPrevented || event.metaKey || event.ctrlKey || event.altKey) {",
    "      return;",
    "    }",
    "",
    "    switch (event.key) {",
    "      case 'ArrowRight':",
    "      case 'PageDown':",
    "      case ' ':",
    "        event.preventDefault();",
    "        moveHorizontal(1);",
    "        break;",
    "      case 'ArrowLeft':",
    "      case 'PageUp':",
    "        event.preventDefault();",
    "        moveHorizontal(-1);",
    "        break;",
    "      case 'ArrowDown':",
    "        event.preventDefault();",
    "        moveVertical(1);",
    "        break;",
    "      case 'ArrowUp':",
    "        event.preventDefault();",
    "        moveVertical(-1);",
    "        break;",
    "      case 'Home':",
    "        event.preventDefault();",
    "        render({ x: 1, y: 0 });",
    "        break;",
    "      case 'End':",
    "        event.preventDefault();",
    "        render({ x: maxX, y: 0 });",
    "        break;",
    "      case 'Escape':",
    "        event.preventDefault();",
    "        exitPresentationMode();",
    "        break;",
    "      case 'n':",
    "      case 'N':",
    "        event.preventDefault();",
    "        playNarration();",
    "        break;",
    "      default:",
    "        break;",
    "    }",
    "  });",
    "",
    "  window.addEventListener('hashchange', function () {",
    "    cancelNarration();",
    "    renderHash();",
    "  });",
    "  document.querySelectorAll('[data-narration-action]').forEach(function (button) {",
    "    button.addEventListener('click', function () {",
    "      const action = button.getAttribute('data-narration-action');",
    "      if (action === 'play') {",
    "        playNarration();",
    "      } else if (action === 'pause') {",
    "        pauseNarration();",
    "      } else if (action === 'stop') {",
    "        cancelNarration();",
    "        setNarrationStatus('Narration stopped.');",
    "      } else if (action === 'toggle') {",
    "        toggleNarrationCollapsed();",
    "      }",
    "    });",
    "  });",
    "  if (narrationVoice) {",
    "    narrationVoice.addEventListener('change', function () {",
    "      try {",
    "        window.sessionStorage.setItem('slideotter:narration-voice', String(narrationVoice.value || ''));",
    "      } catch (error) {",
    "        // Session storage can be unavailable in constrained browser contexts.",
    "      }",
    "    });",
    "  }",
    "  if (speechAvailable()) {",
    "    populateNarrationVoices();",
    "    if (typeof window.speechSynthesis.addEventListener === 'function') {",
    "      window.speechSynthesis.addEventListener('voiceschanged', populateNarrationVoices);",
    "    } else {",
    "      window.speechSynthesis.onvoiceschanged = populateNarrationVoices;",
    "    }",
    "  }",
    "  window.addEventListener('beforeunload', cancelNarration);",
    "  window.addEventListener('resize', syncScale);",
    "  if (window.visualViewport) {",
    "    window.visualViewport.addEventListener('resize', syncScale);",
    "    window.visualViewport.addEventListener('scroll', syncScale);",
    "  }",
    "  try {",
    "    setNarrationCollapsed(window.sessionStorage.getItem('slideotter:narration-collapsed') === 'true');",
    "  } catch (error) {",
    "    setNarrationCollapsed(false);",
    "  }",
    "  syncScale();",
    "  renderHash();",
    "})();"
  ].join("\n");
}
